# These are supported funding model platforms

custom: [https://www.buymeacoffee.com/ndungutse, https://www.patreon.com/user?u=83557555]
liberapay: ndungutse
ko_fi: ndungutsecharles
open_collective: ndungutse-charles
github: NdungutseCharles103
patreon: ndungutsecharles
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
